=== GANys/data-quality/cityjson-spec/1.0.1/cityjson.schema.json
{  "$id": "cityjson.schema.json",  "$schema": "http://json-schema.org/draft-07/schema#",  "title": "CityJSON v1.0.1",  "description": "CityJSON specifications v1.0.0",  "type": "object",  "properties": {    "type": {      "enum": [        "CityJSON"      ]    },    "version": {      "type": "string",      "pattern": "^(\\d\\.)(\\d)$"    },    "metadata": {      "type": "object",      "$ref": "metadata.schema.json#/metadata"    },    "extensions": {      "type": "object",      "additionalProperties": {        "type": "object",        "properties": {          "url": {            "type": "string",            "format": "uri-reference"          },          "version": {            "type": "string",            "pattern": "^(\\d\\.)(\\d)$"          }        },        "required": [          "url",          "version"        ]      }    },    "CityObjects": {      "type": "object",      "additionalProperties": {        "oneOf": [          {            "$ref": "cityobjects.schema.json#/CityObjectGroup"          },          {            "$ref": "cityobjects.schema.json#/Building"          },          {            "$ref": "cityobjects.schema.json#/BuildingPart"          },          {            "$ref": "cityobjects.schema.json#/BuildingInstallation"          },          {            "$ref": "cityobjects.schema.json#/Road"          },          {            "$ref": "cityobjects.schema.json#/Railway"          },          {            "$ref": "cityobjects.schema.json#/TransportSquare"          },          {            "$ref": "cityobjects.schema.json#/TINRelief"          },          {            "$ref": "cityobjects.schema.json#/WaterBody"          },          {            "$ref": "cityobjects.schema.json#/LandUse"          },          {            "$ref": "cityobjects.schema.json#/GenericCityObject"          },          {            "$ref": "cityobjects.schema.json#/CityFurniture"          },          {            "$ref": "cityobjects.schema.json#/SolitaryVegetationObject"          },          {            "$ref": "cityobjects.schema.json#/PlantCover"          },          {            "$ref": "cityobjects.schema.json#/Bridge"          },          {            "$ref": "cityobjects.schema.json#/BridgePart"          },          {            "$ref": "cityobjects.schema.json#/BridgeInstallation"          },          {            "$ref": "cityobjects.schema.json#/BridgeConstructionElement"          },          {            "$ref": "cityobjects.schema.json#/Tunnel"          },          {            "$ref": "cityobjects.schema.json#/TunnelPart"          },          {            "$ref": "cityobjects.schema.json#/TunnelInstallation"          },          {            "$ref": "cityobjects.schema.json#/ExtensionObject"          }        ]      }    },    "vertices": {      "type": "array",      "items": {        "type": "array",        "items": {          "type": "number"        },        "minItems": 3,        "maxItems": 3      }    },    "transform": {      "type": "object",      "properties": {        "scale": {          "type": "array",          "items": {            "type": "number"          },          "minItems": 3,          "maxItems": 3        },        "translate": {          "type": "array",          "items": {            "type": "number"          },          "minItems": 3,          "maxItems": 3        }      },      "required": [        "scale",        "translate"      ],      "additionalProperties": false    },    "appearance": {      "type": "object",      "$ref": "appearance.schema.json#/appearance"    }  },  "required": [    "type",    "version",    "CityObjects",    "vertices"  ]}

=== GANys/data-quality/data/quality_sample.json
{
  "type": "CityJSON",
  "version": "1.1",
  "extensions": {
    "Quality": {
      "url": "https://raw.githubusercontent.com/TheGreatWizard/data-quality/main/cityjson-spec/1.1/extension/quality.schema.json",
      "version": "1.0"
    }
  },
  "CityObjects": {
    "UUID_bbf25190-b0fa-11eb-a8db-00155d01d30e": {
      "type": "+Zone",
      "geometry": {
        "type": "MultiSurface",
        "boundary": [
          [
            [
              0,
              1,
              2,
              3
            ]
          ]
        ]
      },
      "reliability": 0.96,
      "completenessSet": {
        "isExist": true,
        "completenessAbsence": 0.98,
        "completenessExcess": 1.01,
        "isMesh": false,
        "lod1.0": 0.99,
        "lod2.0": 0.80,
        "lod3.1": 0.01
      },
      "temporalReliability": {
        "measureDate": "2016-10-22",
        "measureTime": "15:23:10+00:00",
        "transience": 36500
      },
      "positionalQuality": {
        "set1": {
          "CE90": {
            "value": 20,
            "uom": "m"
          },
          "LE90": {
            "value": 1,
            "uom": "m"
          }
        }
      },
      "visualQuality": {
        "set1": {
          "textureType": "None"
        }
      }
    },
    "UUID_bbf25190-b0fa-11eb-a8da-00155d01d30e": {
      "type": "Building",
      "geometry": [
        {
          "type": "Solid",
          "lod": "2",
          "boundaries": [
            [
              [
                [
                  0,
                  1,
                  2,
                  3
                ]
              ],
              [
                [
                  1,
                  4,
                  5,
                  2
                ]
              ],
              [
                [
                  4,
                  6,
                  7,
                  5
                ]
              ],
              [
                [
                  6,
                  8,
                  9,
                  7
                ]
              ],
              [
                [
                  8,
                  10,
                  11,
                  9
                ]
              ],
              [
                [
                  10,
                  0,
                  3,
                  11
                ]
              ],
              [
                [
                  3,
                  2,
                  5,
                  7,
                  9,
                  11
                ]
              ],
              [
                [
                  1,
                  0,
                  10
                ]
              ],
              [
                [
                  10,
                  8,
                  6
                ]
              ],
              [
                [
                  10,
                  6,
                  4
                ]
              ],
              [
                [
                  10,
                  4,
                  1
                ]
              ]
            ]
          ],
          "semantics": {
            "surfaces": [
              {
                "type": "WallSurface",
                "id": "9c73f0bf-083d-4b13-bd6b-8fc8729e9188"
              },
              {
                "type": "WallSurface",
                "id": "e05c46cb-469b-4c6d-ab15-96510a03e62e"
              },
              {
                "type": "WallSurface",
                "id": "355ecab6-7035-456c-be1a-c11e25121e73"
              },
              {
                "type": "WallSurface",
                "id": "ab89183a-50a8-4110-9b1c-626d84cc1c2b"
              },
              {
                "type": "WallSurface",
                "id": "2fc959b0-b1cd-4e72-a9a6-aad429c909d8"
              },
              {
                "type": "WallSurface",
                "id": "7a5fdd0a-94d0-4555-b1c7-f9506c55ae5a"
              },
              {
                "type": "GroundSurface",
                "id": "81bc0845-6d4f-4a78-b039-847b2dc47e5b"
              },
              {
                "type": "RoofSurface",
                "id": "133b2f27-fc78-4daf-b72a-3d2e9e9e65ea"
              }
            ],
            "values": [
              [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                7,
                7,
                7
              ]
            ]
          }
        }
      ],
      "attributes": {
        "+quality-reliability": [
          {
            "reliability": 0.99
          },
          {
            "target": [
              0,
              0
            ],
            "reliability": 0.98
          }
        ],
        "+quality-positionalQuality": {
          "set1": {
            "CE90": {
              "value": 10,
              "uom": "m"
            },
            "LE90": 0.607
          },
          "set2": [
            {
              "target": [
                0,
                2
              ],
              "SE90": 0.6944098475113633,
              "LE90": 0.3484112109312497
            },
            {
              "SE90": 1.25,
              "LE90": 0.63
            }
          ],
          "set3": {
            "targetSurface": [
              0,
              0
            ],
            "position": [
              0.5,
              0,
              0,
              0.5,
              0,
              0.5
            ],
            "azimuth": {
              "value": 90,
              "uom": "dd"
            },
            "elevation": {
              "value": 0,
              "uom": "dd"
            },
            "texture_CE90": {
              "value": 0.26,
              "uom": "m"
            }
          },
          "set4": {
            "targetVertex": 2,
            "positionAccuracy": [
              0.5,
              0,
              0,
              0.5,
              0,
              0.5
            ]
          }
        },
        "+quality-visualQuality": {
          "set1": {
            "textureType": "None"
          }
        },
        "+quality-completeness": 0.88,
        "+quality-temporalReliability": {
          "measureDate": "2017-10-22",
          "measureTime": "10:33:38+00:00",
          "transience": 3650
        }
      }
    }
  },
  "vertices": [
    [
      4399488.65393696,
      3085327.3272593925,
      3425307.784486925
    ],
    [
      4399488.565617051,
      3085327.6346104783,
      3425307.6221746057
    ],
    [
      4399486.03541594,
      3085325.8601998184,
      3425305.63896177
    ],
    [
      4399486.1237357985,
      3085325.55284891,
      3425305.801273996
    ],
    [
      4399492.3672561385,
      3085326.6291746264,
      3425303.6715828306
    ],
    [
      4399489.837052835,
      3085324.8547645407,
      3425301.6883722777
    ],
    [
      4399496.355671977,
      3085325.542418047,
      3425299.555448566
    ],
    [
      4399493.825466374,
      3085323.768008582,
      3425297.5722403917
    ],
    [
      4399496.441936459,
      3085325.212278797,
      3425299.740772173
    ],
    [
      4399493.911730807,
      3085323.4378695223,
      3425297.757563892
    ],
    [
      4399491.242024028,
      3085326.6385806333,
      3425305.098750981
    ],
    [
      4399488.7118213745,
      3085324.864170544,
      3425303.115539604
    ]
  ],
  "metadata": {},
  "appearance": {},
  "transform": {
    "scale": [
      1,
      1,
      1
    ],
    "translate": [
      0,
      0,
      0
    ]
  }
}
